sudo: required

language: dart
dart:
  - stable
with_content_shell: true

services:
  - docker

before_install:
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
  - pub get --packages-dir

script:
  # Run static analysis checks
  - pub run dart_dev format --check
  - pub run dart_dev analyze

  # Run unit tests
  - pub run dart_dev test

  # Run integration tests
  - bash ./tool/scripts/integration_setup_and_run_task.sh

  # Get test coverage data
  - pub run dart_dev coverage --no-html

after_success:
  # Send coverage report to codecov
  - bash ./tool/scripts/codecov.sh
