codecov:
  branch: master
  bot: thomaslevans-wf

coverage:
  status:
    project:
      unit:
        paths:
          - "test/unit/"
      integration:
        paths:
          - "test/integration/"

    patch:
      unit:
        paths:
          - "test/unit/"
      integration:
        paths:
          - "test/integration/"

comment:
  layout: "header, diff"
  branches: null
  behavior: default
  require_changes: false
